name: Build and Release Executable

on:
  push:
    tags:
      - 'v*'  # 当推送的标签以 "v" 开头时触发（例如 v1.0.0）

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 如果有依赖项，安装它们

    - name: Run build.py
      run: |
        python build.py  # 运行你的构建脚本

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/your_script.exe  # 上传生成的 EXE 文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 Token
